name: "Docker Build & Push"

description: "Build and push a docker container image to container registry"

inputs:
  container_registry:
    required: false
    description: "The container registry URL"
    default: 'ghcr.io'
  container_image_name:
    required: false
    description: "Custom container image name - repository name is used by default"
  container_tags:
    required: false
    description: "The container tags to add to the built image"
    default: ${{ github.run_id }}
  push:
    required: false
    description: "True to push the image to the registry after building"
    default: true
  project_subdirectory:
    required: false
    description: "The subdirectory to run the build from relative to the repository root"
    default: '.'
  ghcr_user:
    required: false
    default: ${{ github.actor }}
  ghcr_token:
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry - ${{ inputs.container_registry }}
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.container_registry }}
        username: ${{ inputs.ghcr_user }}
        password: ${{ inputs.ghcr_token }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Set container image name
      id: image_name
      shell: bash
      run: |
        if [ "${INPUT_NAME}" = "" ]
        then
          IMAGE_NAME="${REPO_NAME}"
        else
          IMAGE_NAME="${REPO_NAME}/${INPUT_NAME}"
        fi
        echo "Setting image name to ${IMAGE_NAME}"
        echo ::set-output name=image_name::${IMAGE_NAME}  
      env:
        REPO_NAME: ${{ github.repository }}
        INPUT_NAME: ${{ inputs.container_image_name }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.container_registry }}/${{ steps.image_name.outputs.image_name }}
        tags: |
          ${{ inputs.container_tags }}
          type=ref,event=branch
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.project_subdirectory }} 
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max